Production
fellesdatakatalog/api-access-request-gui pull request #3
Opened 2023-08-15 09:05 UTC by kleivane

🚀

2023-08-15 10:03 UTC, larsksy approved these changes, later dismissed

2023-08-15 11:12 UTC, valosnah requested changes

2023-08-15 11:12 UTC, valosnah commented on deploy/prod/kustomization.yaml
> +namespace: staging
namespace: prod

2023-08-15 18:11 UTC, kleivane commented on deploy/prod/kustomization.yaml
> +namespace: staging
[220c519](https://github.com/fellesdatakatalog/api-access-request-gui/pull/3/commits/220c519b690ceed21f8b74b92739de16cb8a9249)

2023-08-15 19:45 UTC, valosnah reviewed
Det mangler en .github/workflows/deploy-prod,yaml

Den vil være så og si identisk med deploy-staging.yaml, bare endre "dev" til "prod", og namespace.

2023-08-16 07:43 UTC, kleivane commented
> Det mangler en .github/workflows/deploy-prod,yaml
> 
> Den vil være så og si identisk med deploy-staging.yaml, bare endre "dev" til "prod", og namespace.

Yes! Tenkte jeg skulle avvente sikkerhetsgjennomgangen i dag før jeg laget deploy til prod. Så tenkte at workflowen kunne komme seinere

2023-08-16 09:40 UTC, valosnah approved these changes

2023-08-16 13:53 UTC, merged