Swith to new endpoint with minimal userinfo
fellesdatakatalog/api-access-request-gui pull request #5
Opened 2023-08-17 13:40 UTC by kleivane

2023-08-18 14:22 UTC, larsksy approved these changes

2023-08-18 14:43 UTC, jeffreiffers requested changes

2023-08-18 14:43 UTC, jeffreiffers commented on src/components/auth/withAuth.tsx
> +    id: Userinfo;
```suggestion
    user: Userinfo;
```

2023-08-21 08:46 UTC, kleivane commented on src/components/auth/withAuth.tsx
> +    id: Userinfo;
Fikset [089dc4d](https://github.com/fellesdatakatalog/api-access-request-gui/pull/5/commits/089dc4d2c3e4f59a4edeb8202fe359d35cbb2b06)

2023-08-21 08:46 UTC, merged